version: '3.8'
services:
  api:
    restart: always
    build: ./api
    depends_on:
      - db
    ports:
      - '8081:8081'
    volumes:
      - './api:/app'
    command: 'uvicorn app.main:app --host 0.0.0.0 --port 8081'
  db:
    image: 'nouchka/sqlite3:latest'
    restart: on-failure
    container_name: db
    environment:
      MYSQL_PASSWORD: 12345
      MYSQL_USER: root
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - ./db/:/var/lib/mysql'
    ports:
      - '3306:3306'
    tty: true
