version: '3.8'
services:
  api:
    restart: always
    build: ./api
    depends_on:
      - db
    ports:
      - '8000:8000'
    volumes:
      - './api:/app'
    command: 'python main.py'
  client:
    restart: always
    build: ./client
    volumes:
      - './client:/app'
      - /app/node_modules
    ports:
      - '8080:8080'
    stdin_open: true
    environment:
      - CHOKDIR_USERPOOLING=true
    command: npm run dev
  db:
    image: 'nouchka/sqlite3:latest'
    restart: on-failure
    container_name: db
    environment:
      MYSQL_PASSWORD: 12345
      MYSQL_USER: root
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - ./db/:/var/lib/mysql'
    ports:
      - '3306:3306'
    tty: true
