version: '3.8'
services:
  db:
    image: 'nouchka/sqlite3:latest'
    restart: on-failure
    container_name: db
    environment:
      MYSQL_PASSWORD: 12345
      MYSQL_USER: root
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - ./db/:/var/lib/mysql'
    ports:
      - '3306:3306'
    tty: true
